---
title: jetless.org
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: phil@jetless.org
description: 'Phil Dokas on the world wide web. I like my coffee black and my parole
  denied.'
baseurl: ''
url: http://jetless.org
twitter_username: dokas
github_username: pdokas
permalink: pretty
sass:
  style: compact
plugins:
- jekyll-sitemap
- jekyll-feed
